name: excel_to_json
description: A package that allows you to transform your excel to JSON
version: 1.0.0-dev
homepage: https://github.com/vitoramaral10/excel_to_json

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: '>=2.5.0'

dependencies:
  excel: ^2.0.0-null-safety-3
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.5

dev_dependencies:
  dart_code_metrics: ^4.19.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter