name: excel_to_json
description: A package that allows you to transform excel files to JSON format
  for friendly use in your project.
version: 1.1.0+mkidv.2
homepage: https://github.com/mkidv/excel_to_json

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  excel: ^2.1.0
  file_picker: ^5.2.11
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.1
  flutter_test:
    sdk: flutter
